before_install:
  - sudo apt-get update
  - sudo apt-get install -y libicu-dev

sudo: required
language: go

env:
  ICU_LIB: /usr

go:
  - 1.7
  - 1.8
  - tip

cache:
  directories:
    - vendor

install:
  - make install_ci

script:
  - make test_ci
  - make lint
  - travis_retry goveralls -coverprofile=cover.out -service=travis-ci
