sudo: false
language: go

go:
  - 1.7
  - 1.8
  - tip

cache:
  directories:
    - vendor

install:
  - make install_ci

script:
  - make test_ci
  - make lint
  - travis_retry goveralls -coverprofile=cover.out -service=travis-ci
